version: '3.8'

services:
  app:
    build:
      context: .
      target: base
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/landing_pad_ai_agents
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - rabbitmq
      - redis
    networks:
      - landing-pad-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - landing-pad-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - landing-pad-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - landing-pad-network

networks:
  landing-pad-network:
    driver: bridge

volumes:
  mongodb-data:
  rabbitmq-data:
  redis-data: