version: '3.8'

services:
  app:
    build:
      context: .
      target: base
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=agents_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - RABBITMQ_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - landing-pad-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=agents_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - landing-pad-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - landing-pad-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - landing-pad-network

networks:
  landing-pad-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:
  redis-data: