name: Security Scan

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit
      continue-on-error: true
    
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'landing-pad-ai-agents'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --scan .
          --suppression ./.github/security/suppressions.xml
          --failOnCVSS 7
          --enableRetired
      continue-on-error: true
    
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: reports/
      
    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: javascript
        queries: security-and-quality
      
    - name: Run ESLint Security Rules
      run: npx eslint . -c .eslintrc.js --no-eslintrc --rulesdir .github/security/eslint-rules